=== ranjeet-h/rh-mi-icon-data/registry/schema/icon.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ranjeet-h/rh-mi-icon-data/master/registry/schema/icon.schema.json",
  "title": "rh-mi icon registry file",
  "type": "object",
  "required": ["name", "style", "viewBox", "paths"],
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^[a-z0-9_]+$"
    },
    "style": {
      "type": "string",
      "enum": ["rounded", "outlined", "sharp"]
    },
    "viewBox": {
      "type": "string"
    },
    "paths": {
      "type": "object",
      "required": ["fill0", "fill1"],
      "properties": {
        "fill0": {
          "type": "string"
        },
        "fill1": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "category": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/stack_hexagon.json
{
  "name": "stack_hexagon",
  "style": "rounded",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "m600-431 100-57q9-5 14.5-14.5T720-523v-114q0-11-5.5-20.5T700-672l-100-57q-9-5-20-5t-20 5l-100 57q-9 5-14.5 14.5T440-637v114q0 11 5.5 20.5T460-488l100 57q9 5 20 5t20-5ZM360-280q-33 0-56.5-23.5T280-360v-440q0-33 23.5-56.5T360-880h440q33 0 56.5 23.5T880-800v440q0 33-23.5 56.5T800-280H360Zm0-80h440v-440H360v440Zm220-220ZM218-164Zm10 79q-33 4-59.5-16T138-154L85-591q-4-33 17-59t54-31h2q17-3 30.5 9t13.5 30q0 15-10.5 26T166-602h-1l54 438 474-58q17-2 30 8t15 27q2 17-8 29.5T703-143L228-85Zm352-427-60-34v-68l60-34 60 34v68l-60 34Z",
    "fill1": "M228-85q-33 5-59.5-15.5T138-154L85-591q-4-33 16-59t53-30l46-6v326q0 66 47 113t113 47h372q-6 24-24 41.5T664-138L228-85Zm132-195q-33 0-56.5-23.5T280-360v-440q0-33 23.5-56.5T360-880h440q33 0 56.5 23.5T880-800v440q0 33-23.5 56.5T800-280H360Zm200-151q9 5 20 5t20-5l100-57q9-5 14.5-14.5T720-523v-114q0-11-5.5-20.5T700-672l-100-57q-9-5-20-5t-20 5l-100 57q-9 5-14.5 14.5T440-637v114q0 11 5.5 20.5T460-488l100 57Z"
  },
  "tags": [
    "stack",
    "hexagon"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/encrypted.json
{
  "name": "encrypted",
  "style": "rounded",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M444-360h72q9 0 15.5-7.5T536-384l-19-105q20-10 31.5-29t11.5-42q0-33-23.5-56.5T480-640q-33 0-56.5 23.5T400-560q0 23 11.5 42t31.5 29l-19 105q-2 9 4.5 16.5T444-360Zm23 275q-6-1-12-3-135-45-215-166.5T160-516v-189q0-25 14.5-45t37.5-29l240-90q14-5 28-5t28 5l240 90q23 9 37.5 29t14.5 45v189q0 140-80 261.5T505-88q-6 2-12 3t-13 1q-7 0-13-1Zm13-79q104-33 172-132t68-220v-189l-240-90-240 90v189q0 121 68 220t172 132Zm0-316Z",
    "fill1": "M444-360h72q9 0 15.5-7.5T536-384l-19-105q20-10 31.5-29t11.5-42q0-33-23.5-56.5T480-640q-33 0-56.5 23.5T400-560q0 23 11.5 42t31.5 29l-19 105q-2 9 4.5 16.5T444-360Zm23 275q-6-1-12-3-135-45-215-166.5T160-516v-189q0-25 14.5-45t37.5-29l240-90q14-5 28-5t28 5l240 90q23 9 37.5 29t14.5 45v189q0 140-80 261.5T505-88q-6 2-12 3t-13 1q-7 0-13-1Z"
  },
  "tags": [
    "encrypted"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/position_top_right.json
{
  "name": "position_top_right",
  "style": "rounded",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-560H200v560Zm0-560v560-560Zm220 200h240q25 0 42.5-17.5T720-620q0-25-17.5-42.5T660-680H420q-25 0-42.5 17.5T360-620q0 25 17.5 42.5T420-560Z",
    "fill1": "M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm220-440h240q25 0 42.5-17.5T720-620q0-25-17.5-42.5T660-680H420q-25 0-42.5 17.5T360-620q0 25 17.5 42.5T420-560Z"
  },
  "tags": [
    "position",
    "top",
    "right"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/monitoring.json
{
  "name": "monitoring",
  "style": "rounded",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M131.5-131.5Q120-143 120-160v-40q0-17 11.5-28.5T160-240q17 0 28.5 11.5T200-200v40q0 17-11.5 28.5T160-120q-17 0-28.5-11.5Zm160 0Q280-143 280-160v-220q0-17 11.5-28.5T320-420q17 0 28.5 11.5T360-380v220q0 17-11.5 28.5T320-120q-17 0-28.5-11.5Zm160 0Q440-143 440-160v-140q0-17 11.5-28.5T480-340q17 0 28.5 11.5T520-300v140q0 17-11.5 28.5T480-120q-17 0-28.5-11.5Zm160 0Q600-143 600-160v-200q0-17 11.5-28.5T640-400q17 0 28.5 11.5T680-360v200q0 17-11.5 28.5T640-120q-17 0-28.5-11.5Zm160 0Q760-143 760-160v-360q0-17 11.5-28.5T800-560q17 0 28.5 11.5T840-520v360q0 17-11.5 28.5T800-120q-17 0-28.5-11.5ZM560-481q-16 0-30.5-6T503-504L400-607 188-395q-12 12-28.5 11.5T131-396q-11-12-10.5-28.5T132-452l211-211q12-12 26.5-17.5T400-686q16 0 31 5.5t26 17.5l103 103 212-212q12-12 28.5-11.5T829-771q11 12 10.5 28.5T828-715L617-504q-11 11-26 17t-31 6Z",
    "fill1": "M131.5-131.5Q120-143 120-160v-40q0-17 11.5-28.5T160-240q17 0 28.5 11.5T200-200v40q0 17-11.5 28.5T160-120q-17 0-28.5-11.5Zm160 0Q280-143 280-160v-220q0-17 11.5-28.5T320-420q17 0 28.5 11.5T360-380v220q0 17-11.5 28.5T320-120q-17 0-28.5-11.5Zm160 0Q440-143 440-160v-140q0-17 11.5-28.5T480-340q17 0 28.5 11.5T520-300v140q0 17-11.5 28.5T480-120q-17 0-28.5-11.5Zm160 0Q600-143 600-160v-200q0-17 11.5-28.5T640-400q17 0 28.5 11.5T680-360v200q0 17-11.5 28.5T640-120q-17 0-28.5-11.5Zm160 0Q760-143 760-160v-360q0-17 11.5-28.5T800-560q17 0 28.5 11.5T840-520v360q0 17-11.5 28.5T800-120q-17 0-28.5-11.5ZM560-481q-16 0-30.5-6T503-504L400-607 188-395q-12 12-28.5 11.5T131-396q-11-12-10.5-28.5T132-452l211-211q12-12 26.5-17.5T400-686q16 0 31 5.5t26 17.5l103 103 212-212q12-12 28.5-11.5T829-771q11 12 10.5 28.5T828-715L617-504q-11 11-26 17t-31 6Z"
  },
  "tags": [
    "monitoring"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/keyboard_onscreen.json
{
  "name": "keyboard_onscreen",
  "style": "rounded",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M360-280h240q17 0 28.5-11.5T640-320q0-17-11.5-28.5T600-360H360q-17 0-28.5 11.5T320-320q0 17 11.5 28.5T360-280ZM160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h640q33 0 56.5 23.5T880-720v480q0 33-23.5 56.5T800-160H160Zm0-440h640v-120H160v120Zm0 360h640v-280H160v280Zm0 0v-280 280Zm108.5-171.5Q280-423 280-440t-11.5-28.5Q257-480 240-480t-28.5 11.5Q200-457 200-440t11.5 28.5Q223-400 240-400t28.5-11.5Zm120 0Q400-423 400-440t-11.5-28.5Q377-480 360-480t-28.5 11.5Q320-457 320-440t11.5 28.5Q343-400 360-400t28.5-11.5Zm120 0Q520-423 520-440t-11.5-28.5Q497-480 480-480t-28.5 11.5Q440-457 440-440t11.5 28.5Q463-400 480-400t28.5-11.5Zm120 0Q640-423 640-440t-11.5-28.5Q617-480 600-480t-28.5 11.5Q560-457 560-440t11.5 28.5Q583-400 600-400t28.5-11.5Zm120 0Q760-423 760-440t-11.5-28.5Q737-480 720-480t-28.5 11.5Q680-457 680-440t11.5 28.5Q703-400 720-400t28.5-11.5Z",
    "fill1": "M360-280h240q17 0 28.5-11.5T640-320q0-17-11.5-28.5T600-360H360q-17 0-28.5 11.5T320-320q0 17 11.5 28.5T360-280ZM160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h640q33 0 56.5 23.5T880-720v480q0 33-23.5 56.5T800-160H160Zm0-440h640v-120H160v120Zm108.5 188.5Q280-423 280-440t-11.5-28.5Q257-480 240-480t-28.5 11.5Q200-457 200-440t11.5 28.5Q223-400 240-400t28.5-11.5Zm120 0Q400-423 400-440t-11.5-28.5Q377-480 360-480t-28.5 11.5Q320-457 320-440t11.5 28.5Q343-400 360-400t28.5-11.5Zm120 0Q520-423 520-440t-11.5-28.5Q497-480 480-480t-28.5 11.5Q440-457 440-440t11.5 28.5Q463-400 480-400t28.5-11.5Zm120 0Q640-423 640-440t-11.5-28.5Q617-480 600-480t-28.5 11.5Q560-457 560-440t11.5 28.5Q583-400 600-400t28.5-11.5Zm120 0Q760-423 760-440t-11.5-28.5Q737-480 720-480t-28.5 11.5Q680-457 680-440t11.5 28.5Q703-400 720-400t28.5-11.5Z"
  },
  "tags": [
    "keyboard",
    "onscreen"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/outlined/medication.json
{
  "name": "medication",
  "style": "outlined",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M420-260h120v-100h100v-120H540v-100H420v100H320v120h100v100ZM280-120q-33 0-56.5-23.5T200-200v-440q0-33 23.5-56.5T280-720h400q33 0 56.5 23.5T760-640v440q0 33-23.5 56.5T680-120H280Zm0-80h400v-440H280v440Zm-40-560v-80h480v80H240Zm40 120v440-440Z",
    "fill1": "M420-260h120v-100h100v-120H540v-100H420v100H320v120h100v100ZM280-120q-33 0-56.5-23.5T200-200v-440q0-33 23.5-56.5T280-720h400q33 0 56.5 23.5T760-640v440q0 33-23.5 56.5T680-120H280Zm-40-640v-80h480v80H240Z"
  },
  "tags": [
    "medication"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/outlined/list_alt.json
{
  "name": "list_alt",
  "style": "outlined",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M348.5-291.5Q360-303 360-320t-11.5-28.5Q337-360 320-360t-28.5 11.5Q280-337 280-320t11.5 28.5Q303-280 320-280t28.5-11.5Zm0-160Q360-463 360-480t-11.5-28.5Q337-520 320-520t-28.5 11.5Q280-497 280-480t11.5 28.5Q303-440 320-440t28.5-11.5Zm0-160Q360-623 360-640t-11.5-28.5Q337-680 320-680t-28.5 11.5Q280-657 280-640t11.5 28.5Q303-600 320-600t28.5-11.5ZM440-280h240v-80H440v80Zm0-160h240v-80H440v80Zm0-160h240v-80H440v80ZM200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-560H200v560Zm0-560v560-560Z",
    "fill1": "M348.5-291.5Q360-303 360-320t-11.5-28.5Q337-360 320-360t-28.5 11.5Q280-337 280-320t11.5 28.5Q303-280 320-280t28.5-11.5Zm0-160Q360-463 360-480t-11.5-28.5Q337-520 320-520t-28.5 11.5Q280-497 280-480t11.5 28.5Q303-440 320-440t28.5-11.5Zm0-160Q360-623 360-640t-11.5-28.5Q337-680 320-680t-28.5 11.5Q280-657 280-640t11.5 28.5Q303-600 320-600t28.5-11.5ZM440-280h240v-80H440v80Zm0-160h240v-80H440v80Zm0-160h240v-80H440v80ZM200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Z"
  },
  "tags": [
    "list",
    "alt"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/sauna.json
{
  "name": "sauna",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M80-80v-800h800v800H80Zm80-240v160h80v-80h-40v-80h-40Zm0-80h40v-40h40v-100q0-25 17.5-42.5T300-600h80q25 0 42.5 17.5T440-540v100h40v40h320v-400H160v400Zm100 100h160v-80H260v80Zm80-340q-25 0-42.5-17.5T280-700q0-25 17.5-42.5T340-760q25 0 42.5 17.5T400-700q0 25-17.5 42.5T340-640Zm-20 480h40v-80h-40v80Zm120 0h360v-160H480v80h-40v80Zm50-400q2-13 2.5-19.5t.5-13.5q0-11-4.5-21T470-641q-15-19-22.5-38t-7.5-39q0-8 1-16.5l3-25.5h60q-2 11-3 20.5t-1 21.5q0 11 4.5 21.5T520-674q18 22 26 41.5t8 39.5q0 11-1 18t-3 15h-60Zm100 0q2-13 2.5-19.5t.5-13.5q0-11-4.5-21T570-641q-15-19-22.5-38t-7.5-39q0-8 1-16.5l3-25.5h60q-2 11-3 20.5t-1 21.5q0 11 4.5 21.5T620-674q18 22 26 41.5t8 39.5q0 11-1 18t-3 15h-60Zm102 0q2-13 2.5-19.5t.5-13.5q0-11-4.5-21T672-641q-15-19-22.5-38t-7.5-39q0-8 1-16.5l3-25.5h60q-2 11-3 20.5t-1 21.5q0 11 4.5 21.5T722-674q18 22 26 41.5t8 39.5q0 11-1 18t-3 15h-60ZM260-300v-80 80Z",
    "fill1": "M80-80v-800h800v800H80Zm80-240v160h80v-80h-40v-80h-40Zm0-80h40v-40h40v-100q0-25 17.5-42.5T300-600h80q25 0 42.5 17.5T440-540v100h40v40h320v-400H160v400Zm180-240q-25 0-42.5-17.5T280-700q0-25 17.5-42.5T340-760q25 0 42.5 17.5T400-700q0 25-17.5 42.5T340-640Zm-20 480h40v-80h-40v80Zm120 0h360v-160H480v80h-40v80Zm50-400q2-13 2.5-19.5t.5-13.5q0-11-4.5-21T470-641q-15-19-22.5-38t-7.5-39q0-8 1-16.5l3-25.5h60q-2 11-3 20.5t-1 21.5q0 11 4.5 21.5T520-674q18 22 26 41.5t8 39.5q0 11-1 18t-3 15h-60Zm100 0q2-13 2.5-19.5t.5-13.5q0-11-4.5-21T570-641q-15-19-22.5-38t-7.5-39q0-8 1-16.5l3-25.5h60q-2 11-3 20.5t-1 21.5q0 11 4.5 21.5T620-674q18 22 26 41.5t8 39.5q0 11-1 18t-3 15h-60Zm102 0q2-13 2.5-19.5t.5-13.5q0-11-4.5-21T672-641q-15-19-22.5-38t-7.5-39q0-8 1-16.5l3-25.5h60q-2 11-3 20.5t-1 21.5q0 11 4.5 21.5T722-674q18 22 26 41.5t8 39.5q0 11-1 18t-3 15h-60Z"
  },
  "tags": [
    "sauna"
  ]
}
