=== ranjeet-h/rh-mi-icon-data/registry/schema/icon.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ranjeet-h/rh-mi-icon-data/master/registry/schema/icon.schema.json",
  "title": "rh-mi icon registry file",
  "type": "object",
  "required": ["name", "style", "viewBox", "paths"],
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^[a-z0-9_]+$"
    },
    "style": {
      "type": "string",
      "enum": ["rounded", "outlined", "sharp"]
    },
    "viewBox": {
      "type": "string"
    },
    "paths": {
      "type": "object",
      "required": ["fill0", "fill1"],
      "properties": {
        "fill0": {
          "type": "string"
        },
        "fill1": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "category": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/nest_thermostat_sensor.json
{
  "name": "nest_thermostat_sensor",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M480-160q21 0 41.5-3t40.5-8q-20-28-31-61t-11-68q0-19 3.5-36.5T532-371q-26-14-40-42.5T478-480q0-51 25.5-85.5T574-600q38 0 62.5 25.5T668-508q17-6 35-9t37-3q15 0 29.5 1.5T798-512q-6-61-33.5-113.5t-70-91.5Q652-756 597-778t-117-22q-66 0-124.5 25t-102 68.5Q210-663 185-604.5T160-480q0 66 25 124.5t68.5 102Q297-210 355.5-185T480-160Zm69-249q14-24 33.5-44.5T626-488q-2-23-13-47t-39-24q-30 0-41 27.5T522-480q0 23 6.5 42t20.5 29ZM740-80q-29 0-57-7.5T630-110q-36 15-74 22.5T480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q84 0 158 32.5t128.5 88Q821-704 851.5-629T880-470q38 32 59 76t21 94q0 92-64 156T740-80Zm0-80q58 0 99-41t41-99q0-58-41-99t-99-41q-58 0-99 41t-41 99q0 58 41 99t99 41ZM339-360l-37-20 96-171-2-3H292v-41h155v44L339-360Z",
    "fill1": "M480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q84 0 158 32.5t128.5 88Q821-704 851.5-629T880-470q-30-23-66-36.5T740-520q-19 0-37 3t-35 9q-7-41-31.5-66.5T574-600q-45 0-70.5 34.5T478-480q0 38 14 66.5t40 42.5q-5 17-8.5 34.5T520-300q0 59 29 109.5t80 81.5q-36 14-73.5 21.5T480-80Zm69-329q-14-10-20.5-29t-6.5-42q0-24 11-51.5t41-27.5q28 0 39 24t13 47q-24 14-43.5 34.5T549-409Zm191 249q-58 0-99-41t-41-99q0-58 41-99t99-41q58 0 99 41t41 99q0 58-41 99t-99 41ZM339-360l108-191v-44H292v41h104l2 3-96 171 37 20Z"
  },
  "tags": [
    "nest",
    "thermostat",
    "sensor"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/outlined/shutter_speed_add.json
{
  "name": "shutter_speed_add",
  "style": "outlined",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M720-40v-120H600v-80h120v-120h80v120h120v80H800v120h-80ZM360-840v-80h240v80H360ZM480-80q-75 0-140.5-28.5t-114-77q-48.5-48.5-77-114T120-440q0-75 28.5-140.5t77-114q48.5-48.5 114-77T480-800q64 0 121 21t104 58l57-57 56 56-56 58q39 49 59.5 109T840-427q-14-4-31-9t-49-5q0-10-.5-19.5T757-480H596L416-167q16 4 31.5 5.5T480-160q11 0 21-.5t21-2.5q3 20 9.5 40T548-86q-17 3-34 4.5T480-80Zm0-440h268q-18-62-61.5-109T584-700L480-520Zm-70 40 134-232q-16-4-32.5-6t-33.5-2q-45 0-89 14.5T306-660l104 180Zm-206 80h206L276-632q-42 47-62.5 106.5T204-400Zm172 220 104-180H212q18 62 61.5 109T376-180Zm104-260Zm42 277Zm238-278Z",
    "fill1": "M720-40v-120H600v-80h120v-120h80v120h120v80H800v120h-80ZM360-840v-80h240v80H360ZM480-80q-75 0-140.5-28.5T225-186q-49-49-77-114.5T120-440q0-74 28.5-139.5T226-694q49-49 114.5-77.5T480-800q63 0 120 21t104 59l58-58 56 56-56 58q38 49 59 109.5T840-427q-14-5-35.5-9t-44.5-4q0-116-82-198t-198-82q-117 0-198.5 81.5T200-440q0 117 81.5 198.5T480-160q11 0 21-.5t21-2.5q3 20 9.5 39.5T548-86q-17 3-34 4.5T480-80Zm40-123q1-45 16.5-84t42.5-70q27-31 63-51.5t78-28.5q0-11-1-21.5t-3-21.5H597L436-204q18 4 44 3.5t40-2.5Zm-40-317h226q-18-51-56-89.5T564-665l-84 145Zm-69 40 113-196q-51-10-102.5 3T327-625l84 145Zm-167 80h167L298-596q-35 39-49 90.5T244-400Zm152 185 84-145H254q17 50 55.5 89t86.5 56Z"
  },
  "tags": [
    "shutter",
    "speed",
    "add"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/commit.json
{
  "name": "commit",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M352.5-325.5Q298-371 284-440H80v-80h204q14-69 68.5-114.5T480-680q73 0 127.5 45.5T676-520h204v80H676q-14 69-68.5 114.5T480-280q-73 0-127.5-45.5ZM480-360q50 0 85-35t35-85q0-50-35-85t-85-35q-50 0-85 35t-35 85q0 50 35 85t85 35Z",
    "fill1": "M352.5-325.5Q298-371 284-440H80v-80h204q14-69 68.5-114.5T480-680q73 0 127.5 45.5T676-520h204v80H676q-14 69-68.5 114.5T480-280q-73 0-127.5-45.5ZM480-360q50 0 85-35t35-85q0-50-35-85t-85-35q-50 0-85 35t-35 85q0 50 35 85t85 35Z"
  },
  "tags": [
    "commit"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/face_5.json
{
  "name": "face_5",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M466-726q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-160 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm280 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-320 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm160 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-120 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-240 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm160 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-480 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40-40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80-80q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40-40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 80q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6ZM324.5-404.5Q310-419 310-440t14.5-35.5Q339-490 360-490t35.5 14.5Q410-461 410-440t-14.5 35.5Q381-390 360-390t-35.5-14.5Zm240 0Q550-419 550-440t14.5-35.5Q579-490 600-490t35.5 14.5Q650-461 650-440t-14.5 35.5Q621-390 600-390t-35.5-14.5ZM480-80q-82 0-155-31.5t-127.5-86Q143-252 111.5-325T80-480q0-83 31.5-156t86-127Q252-817 325-848.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 82-31.5 155T763-197.5q-54 54.5-127 86T480-80Zm0-80q134 0 227-93.5T800-480q0-134-93-227t-227-93q-133 0-226.5 93T160-480q0 133 93.5 226.5T480-160Z",
    "fill1": "M466-726q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-160 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm280 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-320 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm160 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-120 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-240 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm160 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm-480 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40-40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80-80q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40-40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 0q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm80 80q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6Zm40 40q-6-6-6-14t6-14q6-6 14-6t14 6q6 6 6 14t-6 14q-6 6-14 6t-14-6ZM324.5-404.5Q310-419 310-440t14.5-35.5Q339-490 360-490t35.5 14.5Q410-461 410-440t-14.5 35.5Q381-390 360-390t-35.5-14.5Zm240 0Q550-419 550-440t14.5-35.5Q579-490 600-490t35.5 14.5Q650-461 650-440t-14.5 35.5Q621-390 600-390t-35.5-14.5ZM480-80q-82 0-155-31.5t-127.5-86Q143-252 111.5-325T80-480q0-83 31.5-156t86-127Q252-817 325-848.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 82-31.5 155T763-197.5q-54 54.5-127 86T480-80Zm0-80q134 0 227-93.5T800-480q0-134-93-227t-227-93q-133 0-226.5 93T160-480q0 133 93.5 226.5T480-160Z"
  },
  "tags": [
    "face",
    "5"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/outlined/settings_system_daydream.json
{
  "name": "settings_system_daydream",
  "style": "outlined",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M360-320h260q42 0 71-29t29-71q0-42-29-71t-71-29h-2q-8-51-44.5-85.5T486-640q-42 0-78 21t-54 59h-5q-47 0-78 36t-31 84q0 50 35 85t85 35Zm0-80q-17 0-28.5-11.5T320-440q0-17 11.5-28.5T360-480h50v-10q0-29 20.5-49.5T480-560q29 0 49.5 20.5T550-490v50h70q8 0 14 6t6 14q0 8-6 14t-14 6H360ZM160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h640q33 0 56.5 23.5T880-720v480q0 33-23.5 56.5T800-160H160Zm0-80h640v-480H160v480Zm0 0v-480 480Z",
    "fill1": "M360-320h260q42 0 71-29t29-71q0-42-29-71t-71-29h-2q-8-51-44.5-85.5T486-640q-42 0-78 21t-54 59h-5q-47 0-78 36t-31 84q0 50 35 85t85 35Zm120-160ZM160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h640q33 0 56.5 23.5T880-720v480q0 33-23.5 56.5T800-160H160Z"
  },
  "tags": [
    "settings",
    "system",
    "daydream"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/edit_arrow_up.json
{
  "name": "edit_arrow_up",
  "style": "rounded",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M160-240q-17 0-28.5-11.5T120-280v-90q0-16 6.5-30.5T144-426l271-271q24-24 57.5-23t56.5 25l48 50q23 23 22.5 56T576-533L306-263q-11 11-25.5 17t-30.5 6h-90Zm40-80h50l162-162-25-25-25-25-162 162v50Zm269-219-50-50 50 50Zm271-109-24 24q-11 11-28 11t-28-11q-11-11-11-28t11-28l92-92q12-12 28-12t28 12l92 92q11 12 11 28.5T899-624q-12 11-28.5 11.5T843-624l-23-23v447q0 17-11.5 28.5T780-160q-17 0-28.5-11.5T740-200v-448Z",
    "fill1": "M160-240q-17 0-28.5-11.5T120-280v-90q0-16 6.5-30.5T144-426l271-271q24-24 57.5-23t56.5 25l48 50q23 23 22.5 56T576-533L306-263q-11 11-25.5 17t-30.5 6h-90Zm309-299 50-51-49-49-51 50 50 50Zm271-109-24 24q-11 11-28 11t-28-11q-11-11-11-28t11-28l92-92q12-12 28-12t28 12l92 92q11 12 11 28.5T899-624q-12 11-28.5 11.5T843-624l-23-23v447q0 17-11.5 28.5T780-160q-17 0-28.5-11.5T740-200v-448Z"
  },
  "tags": [
    "edit",
    "arrow",
    "up"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/military_tech.json
{
  "name": "military_tech",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M280-880h400v362L500-412l28 92h152l-124 88 48 152-124-94-124 94 48-152-124-88h152l28-92-180-106v-362Zm80 80v234l80 48v-282h-80Zm240 0h-80v282l80-48v-234ZM480-647Zm-40-12Zm80 0Z",
    "fill1": "m356-80 48-152-124-88h152l28-92-180-106v-362h400v362L500-412l28 92h152l-124 88 48 152-124-94-124 94Zm124-414 40-24v-282h-80v282l40 24Z"
  },
  "tags": [
    "military",
    "tech"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/outlined/align_self_stretch.json
{
  "name": "align_self_stretch",
  "style": "outlined",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M80-800v-80h800v80H80Zm0 720v-80h800v80H80Zm340-180v-460h120v460H420Z",
    "fill1": "M80-800v-80h800v80H80Zm0 720v-80h800v80H80Zm340-180v-460h120v460H420Z"
  },
  "tags": [
    "align",
    "self",
    "stretch"
  ]
}
