=== ranjeet-h/rh-mi-icon-data/registry/schema/icon.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ranjeet-h/rh-mi-icon-data/master/registry/schema/icon.schema.json",
  "title": "rh-mi icon registry file",
  "type": "object",
  "required": ["name", "style", "viewBox", "paths"],
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^[a-z0-9_]+$"
    },
    "style": {
      "type": "string",
      "enum": ["rounded", "outlined", "sharp"]
    },
    "viewBox": {
      "type": "string"
    },
    "paths": {
      "type": "object",
      "required": ["fill0", "fill1"],
      "properties": {
        "fill0": {
          "type": "string"
        },
        "fill1": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "category": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/transition_push.json
{
  "name": "transition_push",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M320-160v-79h80v-481h-80v-80h160v640H320Zm240 0v-640h360v640H560Zm80-79h200v-481H640v481Zm-440-81-57-56 63-64H40v-80h166l-63-63 57-57 160 160-160 160Zm440 81v-481 481Z",
    "fill1": "M320-160v-79h80v-481h-80v-80h160v640H320Zm240 0v-640h360v640H560ZM200-320l-57-56 63-64H40v-80h166l-63-63 57-57 160 160-160 160Z"
  },
  "tags": [
    "transition",
    "push"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/background_grid_small.json
{
  "name": "background_grid_small",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M200-200h80v-80h-80v80Zm160 0h80v-80h-80v80Zm160 0h80v-80h-80v80Zm160 0h80v-80h-80v80ZM200-680h80v-80h-80v80Zm0 160h80v-80h-80v80Zm0 160h80v-80h-80v80Zm160-320h80v-80h-80v80Zm0 160h80v-80h-80v80Zm0 160h80v-80h-80v80Zm160-320h80v-80h-80v80Zm0 160h80v-80h-80v80Zm0 160h80v-80h-80v80Zm160-320h80v-80h-80v80Zm0 160h80v-80h-80v80Zm0 160h80v-80h-80v80ZM120-120v-720h720v720H120Z",
    "fill1": "M120-120h120v-120H120v120Zm200 0h120v-120H320v120Zm200 0h120v-120H520v120Zm200 0h120v-120H720v120ZM120-720h120v-120H120v120Zm0 200h120v-120H120v120Zm0 200h120v-120H120v120Zm200-400h120v-120H320v120Zm0 200h120v-120H320v120Zm0 200h120v-120H320v120Zm200-400h120v-120H520v120Zm0 200h120v-120H520v120Zm0 200h120v-120H520v120Zm200-400h120v-120H720v120Zm0 200h120v-120H720v120Zm0 200h120v-120H720v120Z"
  },
  "tags": [
    "background",
    "grid",
    "small"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/sports_volleyball.json
{
  "name": "sports_volleyball",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M782-582q-31-87-101-145.5T520-798v64l262 152ZM320-434l120-70v-294q-32 3-62 14.5T320-756v322Zm-134 78 54-32v-302q-39 44-59.5 98T160-480q0 32 6.5 63.5T186-356Zm134 152 280-160-120-70-254 148q20 25 43 46t51 36Zm160 44q75 0 142-34t112-94l-54-30-264 152q16 3 32 4.5t32 1.5Zm294-196q13-29 19.5-60.5T800-480L520-642v138l254 148ZM480-480Zm0 400q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Z",
    "fill1": "M864-592 520-791v-87q123 12 216 90.5T864-592ZM270-404v-416q39-23 82-38t89-20v375l-171 99Zm-154 89q-18-38-27-79.5T80-480q0-77 28-147.5T190-754v395l-74 44Zm176 187q-42-20-76-50t-60-68l325-188 171 99-360 207Zm189 48q-23 0-47-2.5T388-91l344-198 74 41q-57 78-142.5 123T481-80Zm364-236L520-503v-197l360 209q0 46-8 90t-27 85Z"
  },
  "tags": [
    "sports",
    "volleyball"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/outlined/devices.json
{
  "name": "devices",
  "style": "outlined",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M480-540ZM80-160v-80h400v80H80Zm120-120q-33 0-56.5-23.5T120-360v-360q0-33 23.5-56.5T200-800h560q33 0 56.5 23.5T840-720H200v360h280v80H200Zm600 40v-320H640v320h160Zm-180 80q-25 0-42.5-17.5T560-220v-360q0-25 17.5-42.5T620-640h200q25 0 42.5 17.5T880-580v360q0 25-17.5 42.5T820-160H620Zm100-300q13 0 21.5-9t8.5-21q0-13-8.5-21.5T720-520q-12 0-21 8.5t-9 21.5q0 12 9 21t21 9Zm0 60Z",
    "fill1": "M200-280q-33 0-56.5-23.5T120-360v-360q0-33 23.5-56.5T200-800h560q33 0 56.5 23.5T840-720H620q-58 0-99 41t-41 99v300H200Zm420 120q-25 0-42.5-17.5T560-220v-360q0-25 17.5-42.5T620-640h200q25 0 42.5 17.5T880-580v360q0 25-17.5 42.5T820-160H620Zm-540 0v-80h400v80H80Zm640-300q13 0 21.5-9t8.5-21q0-13-8.5-21.5T720-520q-12 0-21 8.5t-9 21.5q0 12 9 21t21 9Z"
  },
  "tags": [
    "devices"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/18_up_rating.json
{
  "name": "18_up_rating",
  "style": "rounded",
  "viewBox": "0 0 24 24",
  "paths": {
    "fill0": "M340-540v150q0 13 8.5 21.5T370-360q13 0 21.5-8.5T400-390v-180q0-13-8.5-21.5T370-600h-60q-13 0-21.5 8.5T280-570q0 13 8.5 21.5T310-540h30Zm160 180h100q17 0 28.5-11.5T640-400v-160q0-17-11.5-28.5T600-600H500q-17 0-28.5 11.5T460-560v160q0 17 11.5 28.5T500-360Zm20-40v-60h60v60h-60Zm0-100v-60h60v60h-60ZM200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-560H200v560Zm0-560v560-560Z",
    "fill1": "M340-540v150q0 13 8.5 21.5T370-360q13 0 21.5-8.5T400-390v-180q0-13-8.5-21.5T370-600h-60q-13 0-21.5 8.5T280-570q0 13 8.5 21.5T310-540h30Zm160 180h100q17 0 28.5-11.5T640-400v-160q0-17-11.5-28.5T600-600H500q-17 0-28.5 11.5T460-560v160q0 17 11.5 28.5T500-360Zm20-40v-60h60v60h-60Zm0-100v-60h60v60h-60ZM200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Z"
  },
  "tags": [
    "18",
    "up",
    "rating"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/circle.json
{
  "name": "circle",
  "style": "rounded",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z",
    "fill1": "M480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Z"
  },
  "tags": [
    "circle"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/sharp/tactic.json
{
  "name": "tactic",
  "style": "sharp",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "m656-120-56-56 63-64-63-63 56-57 64 64 63-64 57 57-64 63 64 64-57 56-63-63-64 63Zm-387.5-91.5Q280-223 280-240t-11.5-28.5Q257-280 240-280t-28.5 11.5Q200-257 200-240t11.5 28.5Q223-200 240-200t28.5-11.5ZM240-120q-50 0-85-35t-35-85q0-50 35-85t85-35q37 0 67.5 20.5T352-284q39-11 63.5-43t24.5-73v-160q0-83 58.5-141.5T640-760h46l-63-63 57-57 160 160-160 160-57-56 63-64h-46q-50 0-85 35t-35 85v160q0 73-47 128.5T354-203q-12 37-43.5 60T240-120Zm-64-480-56-56 63-64-63-63 56-57 64 64 63-64 57 57-64 63 64 64-57 56-63-63-64 63Z",
    "fill1": "m656-120-56-56 63-64-63-63 56-57 64 64 63-64 57 57-64 63 64 64-57 56-63-63-64 63Zm-387.5-91.5Q280-223 280-240t-11.5-28.5Q257-280 240-280t-28.5 11.5Q200-257 200-240t11.5 28.5Q223-200 240-200t28.5-11.5ZM240-120q-50 0-85-35t-35-85q0-50 35-85t85-35q37 0 67.5 20.5T352-284q39-11 63.5-43t24.5-73v-160q0-83 58.5-141.5T640-760h46l-63-63 57-57 160 160-160 160-57-56 63-64h-46q-50 0-85 35t-35 85v160q0 73-47 128.5T354-203q-12 37-43.5 60T240-120Zm-64-480-56-56 63-64-63-63 56-57 64 64 63-64 57 57-64 63 64 64-57 56-63-63-64 63Z"
  },
  "tags": [
    "tactic"
  ]
}

=== ranjeet-h/rh-mi-icon-data/registry/rounded/lunch_dining.json
{
  "name": "lunch_dining",
  "style": "rounded",
  "viewBox": "0 -960 960 960",
  "paths": {
    "fill0": "M160-120q-33 0-56.5-23.5T80-200v-80q0-17 11.5-28.5T120-320h720q17 0 28.5 11.5T880-280v80q0 33-23.5 56.5T800-120H160Zm0-120v40h640v-40H160Zm263-160q-21 20-77 20t-76-20q-20-20-56-20-28 0-45.5 13.5T121-385q-16 5-28.5-6.5T80-420q0-17 11.5-29.5T119-470q17-9 37-19.5t58-10.5q56 0 76 20t56 20q36 0 57-20t77-20q56 0 77 20t57 20q36 0 56-20t76-20q36 0 57 10t38 19q16 8 27.5 21t11.5 30q0 17-12 28.5t-28 6.5q-29-8-45.5-21.5T750-420q-36 0-58 20t-78 20q-56 0-77-20t-57-20q-36 0-57 20Zm202.5-426.5q71.5 13.5 128 42t91.5 74Q880-665 880-600q0 17-11.5 28.5T840-560H120q-17 0-28.5-11.5T80-600q0-65 35-110.5t91.5-74q56.5-28.5 128-42T480-840q74 0 145.5 13.5ZM480-760q-124 0-207.5 31T166-640h628q-23-58-106.5-89T480-760Zm0 520Zm0-400Z",
    "fill1": "M160-120q-33 0-56.5-23.5T80-200v-80q0-17 11.5-28.5T120-320h720q17 0 28.5 11.5T880-280v80q0 33-23.5 56.5T800-120H160Zm263-280q-21 20-77 20t-76-20q-20-20-56-20-28 0-45.5 13.5T121-385q-16 5-28.5-6.5T80-420q0-17 11.5-29.5T119-470q17-9 37-19.5t58-10.5q56 0 76 20t56 20q36 0 57-20t77-20q56 0 77 20t57 20q36 0 56-20t76-20q36 0 57 10t38 19q16 8 27.5 21t11.5 30q0 17-12 28.5t-28 6.5q-29-8-45.5-21.5T750-420q-36 0-58 20t-78 20q-56 0-77-20t-57-20q-36 0-57 20Zm202.5-426.5q71.5 13.5 128 42t91.5 74Q880-665 880-600q0 17-11.5 28.5T840-560H120q-17 0-28.5-11.5T80-600q0-65 35-110.5t91.5-74q56.5-28.5 128-42T480-840q74 0 145.5 13.5Z"
  },
  "tags": [
    "lunch",
    "dining"
  ]
}
